# Generated by Django 5.0.4 on 2025-01-13 09:52

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', length=20, max_length=20, prefix='', unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', length=20, max_length=20, prefix='', unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', length=20, max_length=20, prefix='', unique=True),
        ),
    ]
