# Generated by Django 5.0.4 on 2025-01-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='alluser',
            managers=[
            ],
        ),
    ]
