# Generated by Django 5.0.4 on 2025-01-12 18:05

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_alluser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='alluser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
